name: 💡 Device request
description: Request support for a Tuya device
title: '[Device request]: '
labels:
  - device request

body:
  - type: textarea
    attributes:
      label: Device information
      description: "Please provide us with some information about the device, e.g. the manufacture's website"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Device specification
      description: |
        We will need some information about your device. To retrieve, please:

        - Install the latest version of the Tuya Homey App
        - Add your device as "Other" device
        - Open its settings and copy the specifications from the "Device Specification" setting
        - Paste the value below (replacing the value between ```json and ```)

        The value will look like `{ "device": ..., "specifications": ..., 'data_points': ...}`

        When this information is missing or incorrect, we will need to close your request!
    validations:
      required: true
